# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Hobby.create(title: 'Cooking')
Hobby.create(title: 'Reading')
Hobby.create(title: 'Traveling')
Hobby.create(title: 'Video gaming')
Hobby.create(title: 'Photography')
Hobby.create(title: 'Music')
Hobby.create(title: 'Sport')
Hobby.create(title: 'Board games')
Hobby.create(title: 'Gardening')
Hobby.create(title: 'Fishing')
Work.create(title: 'Healthcare')
Work.create(title: 'Education')
Work.create(title: 'Sales')
Work.create(title: 'Sports')
Work.create(title: 'Marketing')
Work.create(title: 'IT')
Work.create(title: 'Driver')
Work.create(title: 'Insurance')
Work.create(title: 'Bank')
Work.create(title: 'Business')
Work.create(title: 'Art')
Work.create(title: 'Construction')
Work.create(title: 'Rescuer')
Work.create(title: 'Police')
Work.create(title: 'Army')
Work.create(title: 'Beauty')
Work.create(title: 'TV and radio')
Work.create(title: 'Industry')
Work.create(title: 'Fermer')
Work.create(title: 'Other')